name: office_mate
description: "Office Mate"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_database: ^10.5.4
  logger: ^2.2.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/avatars/
